# config.yaml
# === Subject info ===
subinfo_fields:
  - name: subject_id
    type: int
    constraints:
      min: 101
      max: 999
      digits: 3

  - name: session_name
    type: string

  - name: experimenter
    type: string

  - name: gender
    type: choice
    choices: [Male, Female]

subinfo_mapping:
    subject_id: "被试号"
    session_name: "Session名称(Practice/Experiment)"
    experimenter: "主试姓名或缩写"
    gender: "性别"
    Male: "男"
    Female: "女"
    registration_failed: "注册失败。"
    registration_successful: "注册成功！"
    invalid_input: "字段 {field} 输入无效。"


# === Window settings ===
window:
  size: [1920, 1080]
  monitor: testMonitor
  units: deg
  screen: 1
  bg_color: gray
  fullscreen: True

# === Task-level settings ===
task:
  total_blocks: 8 #8
  total_trials: 320 # 320
  trial_per_block: 40 # 40
  conditions: [AB, BA]
  key_list: [f, j]
  left_key: f
  right_key: j
  delta: 10 # points unit
  seed_mode: "same_across_sub"


# === Stimuli  === 
stimuli:
  fixation:
    type: text
    text: "+"
    color: white
  
  win_feedback:
    type: text
    text: "+10分"
    color: green 

  lose_feedback:
    type: text
    text: "-10分"
    color: red
  
  no_response_feedback: 
    type: text
    text: "未反应：-10分"
    color: yellow
    

  stima:
    type: image
    size: [5, 5]
  
  stimb:
    type: image
    size: [5, 5]

  highlight_left:
    type: rect
    lineColor: 'white'
    lineWidth: 3
    fillColor: None
    pos: [-4, -0.3]
    width: 3
    height: 4

  highlight_right:
    type: rect
    lineColor: 'white'
    lineWidth: 3
    fillColor: None
    pos: [4, -0.3]
    width: 3
    height: 4

  block_break:
    type: text
    text: |
      第 {block_num} / {total_blocks} 部分完成
      得分：{score} 分

      请在充分休息后按下空格键
      进入下一个部分
    color: white
    height: 0.78

  instruction_text1:
    type: textbox
    text: |
      【概率性反转学习任务】

      在本任务中，您将看到屏幕上同时出现两个选项
      
      按下 【F】 键 选择左侧
      按下 【J】 键 选择右侧

      每个选项都有一定的获胜概率：
       一开始，某一选项的获胜概率较高
       但请注意，随着任务进行
       选项的获胜概率可能会发生变化！

       按【空格键】进入下一页

    color: white
    font: SimHei
    alignment: center
    letterHeight: 0.78

  instruction_text2:
    type: textbox
    text: |
      您的目标是：
      找出当前更可能获胜的选项
      当规则变化时，及时调整您的选择策略

      请尽量根据反馈信息灵活调整判断
      并尽可能准确地选择当前最佳的选项

      准备好后，请按【空格键】开始任务
    color: white
    font: SimHei
    alignment: center
    letterHeight: 0.78

  good_bye:
    type: text
    text: |
      【任务结束】
      最终得分：{total_score} 分
      感谢您的参与！
      请按【空格键】退出任务。
    color: white
    font: SimHei

# === Timing & Adaptivity ===
timing:
  fixation_duration: [0.6, 0.8]
  cue_duration: 1.5
  feedback_duration: 0.8
 

triggers:
  exp_onset: 98
  exp_end: 99

  block_onset: 100
  block_end: 101

  fixation_onset: 1
  cue_onset: 2
  key_press: 3
  no_response: 4
  win_feedback_onset: 5
  lose_feedback_onset: 6
  no_response_feedback_onset: 7


controller:
  win_prob: 0.8
  rev_win_prob: 0.9
  sliding_window: 10
  sliding_window_hits: 9
